import localFont from "next/font/local";
import "@/src/styles/globals.css";
import 'react-loading-skeleton/dist/skeleton.css'

import {Vazirmatn} from 'next/font/google'
import {CookiesProvider} from "next-client-cookies/server";

// const vazir = Vazirmatn({
//   subsets: ['arabic', 'latin'],
//   display: 'swap'
// })

const vazir = localFont({
    src: '../../assets/fonts/Vazir.woff2',
    display: 'swap'
})

export const metadata = {
    title: "Quiz App",
    description: "Generated by create next app",
}

export default function RootLayout({children, params}) {
    return (
        <html lang={params.lang}
              dir={params.lang === 'en-us' ? 'ltr' : 'rtl'} className={vazir.className}>
        <body>
        <CookiesProvider basename='quiz-app'>
        {children}
        </CookiesProvider>
        </body>
        </html>
    );
}
